name: nestable
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.0'

      - name: build
        run: make build

      - name: vet
        run: make vet

      - name: test
        run: make test
